name: upload-godzilla
on:
  push:
    tags:
       - "mr-[0-9]+"
jobs:
  test:
    name: Run unit test ${{ matrix.go }}
    strategy:
      matrix:
        go: [ '1.16.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: env