name: upload-minilla
on:
  pull_request:
jobs:
  test:
    name: Run unit test ${{ matrix.go }}
    strategy:
      matrix:
        go: [ '1.15.x' ]
    runs-on: ubuntu-latest
    env:
      BUCKET: suzuito-minilla-blog1-article
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: env
      # - run: go run ./cmd/main.go pr 