name: upload-minilla
on:
  push:
    tags:
      - "all-minilla"
jobs:
  test:
    name: Run unit test ${{ matrix.go }}
    strategy:
      matrix:
        go: [ '1.16.x' ]
    runs-on: ubuntu-latest
    env:
      BUCKET: suzuito-minilla-blog1-article
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_MINILLA }}
      GOOGLE_APPLICATION_CREDENTIALS: a.json
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: echo "${GCP_SA_KEY}" > a.json
      - run: go run ./cmd/main.go all